### PR TITLE
Add pending open config

### PR DESCRIPTION
**Pull request by aviatesk**
Thanks for this great package !

I would like to propose that this package allows an user to open an new editor [in a pending state](https://atom.io/docs/api/v1.39.1/Workspace#instance-open) in order to keep the workspace clean, preventing temporarily opened editors from staying there.

### CODE REVIEW

**Comment by t9md** [comment]
Thanks for the PR.
I would like to have following changes.
- `pendingOpen` should be `OpenInPendingState` for explicitness.
- Description be `If the target location is not opened open editor in pending-state(preview mode). `
  - Because I couldn't find version agnostic URL to the fligtht-manual.

**Comment by aviatesk** [comment]
Thanks for your feedback 😉 
Sure thing. I'll follow your suggestions.

**Comment by aviatesk** [comment]
@t9md 
Can you make the new release including this patch ?
I want to make it easier to use this package on different machine in the future.

**Comment by t9md** [comment]
Sorry for my super slow response.
I have just released it.

**Comment by aviatesk** [comment]
No worries, and thanks so much !

**Pull request merged**
