### PR TITLE
option to only save one cursor per file

### PR DESCRIPTION
**Pull request by farfromrefug**
I added an option to only save one cursor position (last one) per file.
This mostly get a navigation like xcode or such.
Something i always wanted!

### CODE REVIEW

**Comment by brunolemos** [comment]
That seems a cool option, but would be more flexible as a new action, like:

```
cursor-history:next-file
cursor-history:prev-file
```

So it would keep saving all the cursors but with the possibility to have a shortcut to go to the last cursor of another file.

**Comment by t9md** [comment]
Thanks for contribution,
But I myself don't need this feature, I'll take @brunolemos 's suggestion as compromise.
So can't directly merge this PR.
Will handle distinct issue #20.

**Comment by brunolemos** [comment]
@t9md don't worry about it, the demand is too small. I don't need this feature neither.

**Comment by t9md** [comment]
I tried, but providing `next-file`, `prev-file` get things very complecated.
OK for previous entry, but when go to **next** It's better to pick latest entry(not oldest entry), but when I try to pick latest entry I have to compact all entries to keep current history index correct.

I don't want to make code complex.
So I changed my mind to pick @farfromrefug 's suggestion, but I implement it by myself.

**Comment by t9md** [comment]
released v0.6.0

**Comment by farfromrefug** [comment]
Thanks @t9md Glad to see you did it your way ;)

**Pull request closed without merging**
